spring.application.name=RelaxUp
spring.jpa.database=postgresql
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost/RelaxUp
spring.datasource.username=postgres
spring.datasource.password=sebas123
server.port=8080